-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 15:18:20 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema seng2050a3_java
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seng2050a3_java` ;

-- -----------------------------------------------------
-- Schema seng2050a3_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seng2050a3_java` DEFAULT CHARACTER SET utf8 ;
USE `seng2050a3_java` ;

-- -----------------------------------------------------
-- Table `seng2050a3_java`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` INT(11) NULL DEFAULT NULL,
  `notification` TINYINT(1) NOT NULL,
  `notification_text` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `role_idx` (`role` ASC),
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `seng2050a3_java`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`issueCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`issueCategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`issueStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`issueStatuses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`issues` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `resolution` LONGTEXT NULL DEFAULT NULL,
  `category` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `resolved` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  INDEX `status_idx` (`status` ASC),
  INDEX `category_idx` (`category` ASC),
  CONSTRAINT `category`
    FOREIGN KEY (`category`)
    REFERENCES `seng2050a3_java`.`issueCategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status`
    FOREIGN KEY (`status`)
    REFERENCES `seng2050a3_java`.`issueStatuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `seng2050a3_java`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `issueId` INT(11) NOT NULL,
  `user` INT(11) NULL DEFAULT NULL,
  `comment` LONGTEXT NOT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT '1',
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `issueId_idx` (`issueId` ASC),
  INDEX `comment_userId` (`user` ASC),
  CONSTRAINT `comment_userId`
    FOREIGN KEY (`user`)
    REFERENCES `seng2050a3_java`.`users` (`id`),
  CONSTRAINT `issueId`
    FOREIGN KEY (`issueId`)
    REFERENCES `seng2050a3_java`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
