-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 10:14:33 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seng2050a3_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seng2050a3_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seng2050a3_java` DEFAULT CHARACTER SET utf8 ;
USE `seng2050a3_java` ;

-- -----------------------------------------------------
-- Table `seng2050a3_java`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`roles` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`roleId`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`users` (
  `usersid` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` INT NULL,
  PRIMARY KEY (`usersid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `role_idx` (`role` ASC),
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `seng2050a3_java`.`roles` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`issueCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`issueCategories` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categoryId`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`issueStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`issueStatuses` (
  `statusId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`statusId`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`issues` (
  `issueId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` BLOB NULL,
  `resolution` BLOB NULL,
  `category` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `resolved` DATETIME NULL,
  `userId` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`issueId`),
  INDEX `userId_idx` (`userId` ASC),
  INDEX `status_idx` (`status` ASC),
  INDEX `category_idx` (`category` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `seng2050a3_java`.`users` (`usersid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status`
    FOREIGN KEY (`status`)
    REFERENCES `seng2050a3_java`.`issueStatuses` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category`
    FOREIGN KEY (`category`)
    REFERENCES `seng2050a3_java`.`issueCategories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seng2050a3_java`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seng2050a3_java`.`comments` (
  `commentId` INT NOT NULL AUTO_INCREMENT,
  `issueId` INT NOT NULL,
  `comment` BLOB NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`commentId`),
  INDEX `issueId_idx` (`issueId` ASC),
  CONSTRAINT `issueId`
    FOREIGN KEY (`issueId`)
    REFERENCES `seng2050a3_java`.`issues` (`issueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
